### PR TITLE
Allow `TensorType.convert_variable` to work with mixed static shapes

### PR DESCRIPTION
**Pull request by ricardoV94**
Fixes issue revealed in https://github.com/aesara-devs/aeppl/pull/181

### CODE REVIEW

**Review by brandonwillard — COMMENTED** [review]
Looks like that `None` case isn't working in at least one test situation.

**Comment by ricardoV94** [comment]
> Looks like that `None` case isn't working in at least one test situation.

Something weird with the use of `convert_variable` in `IfElse`, which looks like it should have been `filter_variable`, since `convert_variable` is supposed to return None when it can't do its job

**Comment by ricardoV94** [comment]
Getting a bit bogged down with sparse/dense conversion types. Not super clear what should and should not be allowed.

**Comment by brandonwillard** [comment]
> Getting a bit bogged down with sparse/dense conversion types. Not super clear what should and should not be allowed.

As I recall, `SparseTensorType` will raise `NotImplementedError`s for dtype and sparsity-format changes.

**Comment by brandonwillard** [comment]
You can change the `pytest.raises` in `test_Sparse_convert_variable` to an `assert ... is None`.

**Comment by brandonwillard** [comment]
Better yet, https://github.com/aesara-devs/aesara/pull/1192 will address these `SparseTensorType` issues.

**Review by brandonwillard — APPROVED** [review]

**Pull request merged**
