### PR TITLE
Migrate from setuptools to hatchling

### PR DESCRIPTION
**Pull request by maresb**
**Base: #1371**

Change the build-backend from setuptools to hatchling.

**Question:** Is there any reason for `docs/` to be included in the sdist? It's not in the wheel.

~For some reason I'm having trouble including the file `aesara/d3viz/html/template.html`. I'm not sure yet why it's being excluded.~

**Thank you for opening a PR!**

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [X] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [x] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [x] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.
+ [ ] There are tests covering the changes introduced in the PR.

Don't worry, your PR doesn't need to be in perfect order to submit it.  As development progresses and/or reviewers request changes, you can always [rewrite the history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) of your feature/PR branches.

If your PR is an ongoing effort and you would like to involve us in the process, simply make it a [draft PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests).

### CODE REVIEW

**Comment by maresb** [comment]
Ok, I think I got it!!! Excludes are now determined by the root `/.gitignore` union additional excludes from `pyproject.toml`. The last few missing files were caused by a few `/.gitignore` rules that were too broad.

Unlike my previous PRs, once #1371 is merged I want to do a "squash and merge" here, so I'm not curating my individual commits.

**Comment by maresb** [comment]
Rebased on latest changes. All tests were green.

**Comment by maresb** [comment]
I made another review pass since I hadn't yet checked the wheel. The `bin/` directory was missing from the wheel, so I reincluded it. I'm feeling fairly confident now that I've done due diligence here.

**Comment by maresb** [comment]
```
Warning: Performance alert! Previous value was 61258.103085955845 and current value is 28070.87678331834. It is 2.182265397650837x worse than previous exceeding a ratio threshold 2
Warning: Performance alert! Previous value was 1.3921410587885548 and current value is 0.6737363168561912. It is 2.066299565510444x worse than previous exceeding a ratio threshold 2
Error: # :warning: **Performance Alert** :warning:
```

**Comment by maresb** [comment]
Still open question: Is there any reason for docs/ to be included in the sdist? It's not in the wheel, and it takes up significant space.

**Comment by brandonwillard** [comment]
> Still open question: Is there any reason for docs/ to be included in the sdist? It's not in the wheel, and it takes up significant space.

Good question; I'm not aware of one at the moment, so we can probably remove it.

**Comment by maresb** [comment]
> > Still open question: Is there any reason for docs/ to be included in the sdist? It's not in the wheel, and it takes up significant space.
> 
> Good question; I'm not aware of one at the moment, so we can probably remove it.

Great, let's do it in the next PR though. (One thing at a time.)

**Review by brandonwillard — APPROVED** [review]

**Comment by maresb** [comment]
Thanks for the approval!

Interesting... if I update the branch with a rebase (via the GH interface), then it discards your approving review. But with a merge update, it retains your approval. (Since I ultimately want to squash-and-merge, the Git history will remain linear.)

**Comment by maresb** [comment]
# Addendum

This PR broke nightly builds. See #1406 for the issue and #1407 for the fix.

**Pull request merged**
