### PR TITLE
GitHub actions: run test workflow on Mac

### LINKED ISSUE #973: Run Github Actions test workflow on Mac OS
Currently, we are not running CI with Mac OS so verifying continued correct behavior on OS X is more difficult. Github Actions provides access to Mac OS Intel machines so we may want to start running these in CI.

### PR DESCRIPTION
**Pull request by tal66**
Hi, I think this will close #973

### CODE REVIEW

**Comment by brandonwillard** [comment]
Thanks for the PR!  This looks good; the only thing we need to consider before merging is if there's a small(er) subset of the tests that we can run.  (We can always go forward with this and find a subset later, though.)

**Comment by brandonwillard** [comment]
I just added some missing `os` entries to the `include`s, so you'll need to rebase locally.

**Review by brandonwillard — COMMENTED** [review]
Looks like we need someone to debug [`tests/link/c/test_cmodule.py::test_cache_race_condition`](https://github.com/aesara-devs/aesara/runs/6720766472?check_suite_focus=true#step:6:950) on a Mac, and/or we can skip that test when it's not run on Linux.

**Comment by tal66** [comment]
I think it has to do with the change in `multiprocessing` on 3.8: "On macOS, the spawn start method is now the default. The fork start method should be considered unsafe as it can lead to crashes of the subprocess."

With something like this the tests will pass on mac:

`@pytest.mark.skipif(
    sys.platform == "darwin" and sys.version_info > (3, 7),
    reason="multiprocessing change in 3.8",
)`

or since i'm not an expert on this, maybe you want to do something else?

**Comment by brandonwillard** [comment]
> With something like this the tests will pass on mac:
> 
> ```
> @pytest.mark.skipif(
>     sys.platform == "darwin" and sys.version_info > (3, 7),
>     reason="multiprocessing change in 3.8",
> )
> def test_cache_race_condition():
> ...
> ```
> 
> or since i'm not an expert on this, maybe you want to do something else?

That's perfectly fine; those tests only need to run on one system.

**Review by brandonwillard — COMMENTED** [review]
It looks like this does max out our parallel job runs in CI and increase the total run time, so we'll have to restrict the MacOS runs to some tests that only address potential Mac-specific issues.

The first thing that comes to mind is the C backend compilation.  The tests in `tests.link.c` should serve as decent smoke tests for basic compilation issues.

Aside from that, we should probably start adding OS-specific tests based on old (and new) issues, and add those to this small subset of OS tests.  That would be an ongoing effort, though.

**Pull request closed without merging**
