### PR TITLE
Add Numba config options

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR adds some Numba config options for `fastmath` and the `target` option for `numba.vectorize`.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
Since you're exposing `fastmath` it would be interesting if using the `svml` also made a difference:

image

https://numba.pydata.org/numba-doc/latest/user/performance-tips.html#intel-svml

**Comment by dhirschfeld** [comment]
Also was wondering if it makes sense to set the `nogil` argument?

**Comment by dhirschfeld** [comment]
...and for `jit` calls, setting the [`error_model`](https://github.com/numba/numba/blob/d0ca288f24eccff3ba1f86e38f0de07a717f8d4c/numba/core/decorators.py#L70-L74) to `numpy` (which I think makes it faster)

**Comment by twiecki** [comment]
Closes https://github.com/aesara-devs/aesara/issues/409.

**Comment by brandonwillard** [comment]
> Since you're exposing `fastmath` it would be interesting if using the `svml` also made a difference:
> 
> image
> 
> https://numba.pydata.org/numba-doc/latest/user/performance-tips.html#intel-svml

We could probably measure something like that via #404; that's where all of these recent Numba updates are coming from.

**Comment by dgerlanc** [comment]
> Since you're exposing `fastmath` it would be interesting if using the `svml` also made a difference:
> 
> image
> 
> https://numba.pydata.org/numba-doc/latest/user/performance-tips.html#intel-svml

I'm not sure if you need to do anything additional to use `SVML` besides have the shared library installed and in `numba`'s path.

**Pull request closed without merging**
