### PR TITLE
Exclude doc/ from sdist

### LINKED ISSUE #1397: Remove doc/ from sdist
According to https://github.com/aesara-devs/aesara/pull/1384#issuecomment-1385319888 it seems that the `docs/` directory isn't doing anything but taking up space from the sdist. (Deleting reduces the `.tar.gz` sdist from 3.85MB to 1.34MB.)

### PR DESCRIPTION
**Pull request by maresb**
It seems that the doc/ directory isn't doing anything but taking up space in the sdist. (Deleting reduces the .tar.gz sdist from 3.85MB to 1.34MB.)

Note: doc/.build/PLACEHOLDER is still included. It's 14 years old now, so perhaps it is unnecessary and can be deleted?

Closes #1397

**Thank you for opening a PR!**

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [X] There is an informative high-level description of the changes.
+ [X] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [X] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [X] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [X] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.
+ [ ] There are tests covering the changes introduced in the PR.

Don't worry, your PR doesn't need to be in perfect order to submit it.  As development progresses and/or reviewers request changes, you can always [rewrite the history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) of your feature/PR branches.

If your PR is an ongoing effort and you would like to involve us in the process, simply make it a [draft PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests).

### CODE REVIEW

**Comment by maresb** [comment]
In the spirit of changing no more than one thing at a time, I don't see any rush on merging this. We may want to wait until after the Hatch stuff is already released and shown to be stable.

**Comment by maresb** [comment]
Strange, this is failing with

```
OSError: License file does not exist: LICENSE.txt
```

This doesn't make any sense to me yet, and it builds for me locally. I wonder if this could be related in some way to https://github.com/aesara-devs/aesara/issues/1409?

I'm out of time right now, so I'll have to come back to this.

**Comment by dgerlanc** [comment]
> Strange, this is failing with
> 
> ```
> OSError: License file does not exist: LICENSE.txt
> ```
> 
> This doesn't make any sense to me yet, and it builds for me locally. I wonder if this could be related in some way to #1409?
> 
> I'm out of time right now, so I'll have to come back to this if someone else doesn't get it first.

`LICENSE.txt` seems to be a symbolic link to `docs/LICENSE.txt`, which I'm guessing is the issue.

**Comment by maresb** [comment]
Thanks @dgerlanc for solving the mystery!

I think it's fairly standard these days to just have `LICENSE.txt` in the project root, and I suspect that `doc/LICENSE.txt` may be some legacy artifact. Let's see if deleting it breaks anything.

**Review by brandonwillard — APPROVED** [review]

**Comment by brandonwillard** [comment]
Thanks as always, @maresb!

**Comment by maresb** [comment]
Thanks for the merge! Results are looking good:
image
image

**Comment by brandonwillard** [comment]
> Thanks for the merge! Results are looking good: image image

Wow, much better!

**Pull request merged**
