### PR TITLE
Add mention of tags and ARM environments to developer start guide

### PR DESCRIPTION
**Pull request by PaulScemama**
Resolves [1457](https://github.com/aesara-devs/aesara/issues/1457)

Very minimal change to the documentation for developer install guide. It

1. adds instruction to collect tags.
2. notes a possible error when using `git://` and gives instruction to resolve if the issue occurs.
3. notes using `environment-arm.yml` when creating conda environment if using ARM processor.

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [x] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [x] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [x] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.
+ [] There are tests covering the changes introduced in the PR.

Not sure how to write a test for this, or if that is even necessary. Let me know!

### CODE REVIEW

**Comment by PaulScemama** [comment]
I had trouble building the documentation myself, but I just used `docutils` to convert `.rst` to `.html` and then rendered the `html` to get an idea of what the changes looked like (since the changes were so small). However, I wouldn't think my local developer (and documentation) environment being troublesome would have an effect on these tests?

**Comment by brandonwillard** [comment]
> I had trouble building the documentation myself, but I just used `docutils` to convert `.rst` to `.html` and then rendered the `html` to get an idea of what the changes looked like (since the changes were so small). However, I wouldn't think my local developer (and documentation) environment being troublesome would have an effect on these tests?

Sorry, there were unrelated docs and test issues that have just been resolved.

**Comment by PaulScemama** [comment]
Ready for review @brandonwillard @rlouf. No rush!

**Review by brandonwillard — APPROVED** [review]
Looks great; thanks!

**Pull request merged**
