### PR TITLE
Fixed issue with NumPy 1.22

### LINKED ISSUE #715: AttributeError on import with new NumPy 1.22
## Description of your problem or feature request

Yesterdays NumPy 1.22.0 release broke some blas config settings.

I first saw it in a CI run today, and it was easily reproduced locally by installing the latest NumPy.

**Please provide the full traceback of any errors.**

```python
>>> import aesara
Traceback (most recent call last):
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\configparser.py", line 239, in fetch_val_for_key
    return self._aesara_cfg.get(section, option)
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'blas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\configparser.py", line 355, in __get__
    val_str = cls.fetch_val_for_key(self.name, delete_key=delete_key)
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\configparser.py", line 243, in fetch_val_for_key
    raise KeyError(key)
KeyError: 'blas__ldflags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\__init__.py", line 79, in <module>
    from aesara import scalar, tensor
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\tensor\__init__.py", line 96, in <module>
    from aesara.tensor import (  # noqa
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\tensor\blas.py", line 166, in <module>
    from aesara.tensor.blas_headers import blas_header_text, blas_header_version
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\tensor\blas_headers.py", line 1015, in <module>
    if not config.blas__ldflags:
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\configparser.py", line 359, in __get__
    val_str = self.default()
  File "C:\Users\zufal\miniconda3\envs\aesara-testing\lib\site-packages\aesara\link\c\cmodule.py", line 2628, in default_blas_ldflags
    blas_info = numpy.distutils.__config__.blas_opt_info
AttributeError: module 'numpy.distutils.__config__' has no attribute 'blas_opt_info'
```

## Versions and main components

* Aesara version: 2.3.3
* ~Aesara config (`python -c "import aesara; print(aesara.config)"`)~
* Python version: confirmed for 3.8, 3.9
* Operating system: confirmed for Linux, Windows
* How did you install Aesara: pip

### PR DESCRIPTION
**Pull request by oscargus**
Removed direct access of numpy config that was removed in NumPy 1.22. Fixes #715 

**Thank you for opening a PR!**

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [x] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [x] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [x] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.
+ [ ] There are tests covering the changes introduced in the PR.

Don't worry, your PR doesn't need to be in perfect order to submit it.  As development progresses and/or reviewers request changes, you can always [rewrite the history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) of your feature/PR branches.

If your PR is an ongoing effort and you would like to involve us in the process, simply make it a [draft PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests).

### CODE REVIEW

**Comment by kc611** [comment]
@oscargus Thank you for the PR. 

Loos like that particular if-else case was just there to access the `blas-info` directly without printing any system related info to the user. Seems to me it was just there for user convenience.

**Comment by oscargus** [comment]
As it was not tested with NumPy 1.22 I added all later Python versions to the tests. Maybe not how it should be in the long run, but to see if the tests can be run with NumPy 1.22...

**Comment by brandonwillard** [comment]
> As it was not tested with NumPy 1.22 I added all later Python versions to the tests. Maybe not how it should be in the long run, but to see if the tests can be run with NumPy 1.22...

It's worth running all these in this PR, but we need to find a lighter weight way of adding new versions, because all these will extending the testing time by too much.  I'll create a separate issue for that, and, once a single run of the PR in this form passes, we can remove those changes and follow up later.

**Comment by oscargus** [comment]
Yes, running all are not really a worthwhile idea. Also, it seems like there are things in 3.10 that are probably compiled as it currently has been installing dependencies for almost half an hour...

Also, I realized that you are installing through mamba and at least recently 1.22 was not available there.

Python 3.6 has reached end of life recently, so at least that can be dropped I guess. Let me know which version I should include and I can push another one, either here or after.

**Comment by brandonwillard** [comment]
> Yes, running all are not really a worthwhile idea. Also, it seems like there are things in 3.10 that are probably compiled as it currently has been installing dependencies for almost half an hour...

Ouch.  Yeah, we'll have to look into that one.

> Also, I realized that you are installing through mamba and at least recently 1.22 was not available there.

Good to know, thanks!  If anything, it seems like we might need to an explicit test for the latest NumPy.


> Python 3.6 has reached end of life recently, so at least that can be dropped I guess. Let me know which version I should include and I can push another one, either here or after.

Yes, we can drop 3.6 and shift the tests to cover 3.7 and 3.9 for now.  We should probably test the upper and lower ranges instead (i.e. 3.7 and 3.10), but I want to look at those 3.10 builds first.

**Comment by oscargus** [comment]
New attempt without 3.6 (obsolete) and 3.10 (long time installing).

**Comment by brandonwillard** [comment]
Looks like [the 3.10 failure](https://github.com/aesara-devs/aesara/runs/4680838635?check_suite_focus=true#step:5:13) might be due to the VM running out of memory during the Mamba install step.

**Comment by brandonwillard** [comment]
All right, everything looks good!  If you don't mind dropping 3.8 from the test matrix, we can merge this right now.

**Comment by oscargus** [comment]
I've dropped 3.8 now, so should be good to go.

**Comment by brandonwillard** [comment]
Much appreciated!

**Pull request merged**
