### PR TITLE
Add a C implementation for `BroadcastTo`

### LINKED ISSUE #1128: Add a C implementation for `BroadcastTo`
We could use a C implementation for `BroadcastTo` now that it's in regular use.

_Originally posted by @mattearllongshot in https://github.com/aesara-devs/aesara/issues/1124#issuecomment-1220690266_

### PR DESCRIPTION
**Pull request by brandonwillard**
Closes #1128

### CODE REVIEW

**Comment by ricardoV94** [comment]
Does the docs build fail mean anything?

**Comment by brandonwillard** [comment]
> Does the docs build fail mean anything?

No, that's unrelated.

**Comment by zoj613** [comment]
Not sure how useful this info is for this implementation since I haven't looked over it yet but numpy has a C function for broadcasting arrays to a particular shape via `PyArray_BroadcastToShape`.

**Comment by brandonwillard** [comment]
> Not sure how useful this info is for this implementation since I haven't looked over it yet but numpy has a C function for broadcasting arrays to a particular shape via [`PyArray_BroadcastToShape`](https://github.com/numpy/numpy/blob/d4baf3641471971552206b02f94323a54b54d99a/numpy/core/src/multiarray/iterators.c#L202-L271). It would be interesting to see the performance difference vs the current approach. [Here](https://github.com/zoj613/polyagamma/blob/7bbba58edb5c2a0396be30545e92afb1de6c6d42/polyagamma/_polyagamma.pyx#L96-L117) is a code snippet where I made use of it in the past (It does not require reference counting).

I believe that's part of the old iterator API.

**Comment by zoj613** [comment]
> > Not sure how useful this info is for this implementation since I haven't looked over it yet but numpy has a C function for broadcasting arrays to a particular shape via [`PyArray_BroadcastToShape`](https://github.com/numpy/numpy/blob/d4baf3641471971552206b02f94323a54b54d99a/numpy/core/src/multiarray/iterators.c#L202-L271). It would be interesting to see the performance difference vs the current approach. [Here](https://github.com/zoj613/polyagamma/blob/7bbba58edb5c2a0396be30545e92afb1de6c6d42/polyagamma/_polyagamma.pyx#L96-L117) is a code snippet where I made use of it in the past (It does not require reference counting).
> 
> I believe that's part of the old iterator API.


What are the advantages of using the new one over the old? I've barely seen any code bases making use of the new one.

**Comment by brandonwillard** [comment]
> What are the advantages of using the new one over the old? I've barely seen any code bases making use of the new one.

Not sure, but I would assume the newer one will be better supported going forward.  All I know is that `np.broadcast_to` appears to use the new one, too, and this implementation is based on that.

**Pull request merged**
