### PR TITLE
Move subtensor rewrites from basic_opt to subtensor_opt

### LINKED ISSUE #545: Move `*Subtensor*` rewrites from `basic_opt` into `subtensor_opt`
The `aesara.tensor.subtensor_opt` module was created recently and we should move all the `*Subtensor*` rewrites that are still in `aesara.tensor.basic_opt` into that module.

### PR DESCRIPTION
**Pull request by spiyer99**
**There is an informative high-level description of the changes.**
Moves the `*Subtensor*` rewrites in `aesara.tensor.basic_opt` to `aesara.tensor.subtensor_opt`. 
Doesn't change too much. This is my first contribution to this repo.

**The description and/or commit message(s) references the relevant GitHub issue(s).**
Resolves #545.

**[`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).**
Yes

**The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.  If your commit description starts with "Fix...", then you're probably making this mistake.**
Yes

### CODE REVIEW

**Review by brandonwillard — COMMENTED** [review]
It looks like `pre-commit` might not be set up correctly in your project environment.

You can use `pre-commit run --all` to rerun all the checks.

**Comment by spiyer99** [comment]
> It looks like `pre-commit` might not be set up correctly in your project environment.
Thanks I think I set it up properly now.

**Comment by brandonwillard** [comment]
OK, now you might've reached a common difficulty: implicit changes in an underlying RNG state that cause tests to fail.

[One of the CI failures](https://github.com/aesara-devs/aesara/pull/551/checks?check_run_id=3371064681#step:6:106), appears to involve an unseeded (or poorly seeded) draw.  Try running this test a few times locally and see if it will occasionally pass.  

If that's the case, then these changes have probably altered the run order of the tests and&mdash;as a result&mdash;changed the draws that this brittle test uses.  The answer would then involve another commit that fixes this test by explicitly creating a seeded RNG and using that (e.g. `rng = np.random.default_rng(98324)` then use `rng.random((5, 10))` instead).

**Comment by spiyer99** [comment]
Thanks @brandonwillard. I changed the `tests/tensor/nnet/test_basic.py` file to include `rng = np.random.default_rng(98324)` and then use rng.random((5, 10)). Let me know if I've done this incorrectly.

Hopefully this passes the CI tests now!

**Comment by spiyer99** [comment]
@brandonwillard just wanted to get an update on this?

**Comment by ricardoV94** [comment]
What is this binary file added in https://github.com/aesara-devs/aesara/pull/551/commits/b6e38b2206ab1cab7312fdc3d9ab16c2242f0a78#diff-fd5f20292bbd6611ea3c7dc0601bca8fcbed2a948cf5ebf9b435766de9305425

**Comment by spiyer99** [comment]
I'm not sure @ricardoV94. Sorry I must've done a `git add .`. I'll remove it and recommit.

**Comment by ricardoV94** [comment]
Thanks @spiyer99 

Could you also merge/drop the extra commits so that this PR only has two commits, the first moving the `opt` and the second seeding the moved test?

**Comment by ricardoV94** [comment]
Also there might be a coffee other opts that the original issue had in mind like

`local_subtensor_remove_broadcastable_index` 

Do you want to address those as well?

**Comment by spiyer99** [comment]
Thanks @ricardoV94 I'll address the other opts and drop the extra commits. I'll get back to you when I'm done.

**Comment by ricardoV94** [comment]
@brandonwillard should we also move opts related to AdvancedSubtensor and/or In subtensor ?

**Comment by brandonwillard** [comment]
> @brandonwillard should we also move opts related to any of `SetSubtensor`, `IncSubtensor`, and `Advanced` variations?
> 
> The description from the original issue does not mention these

Yes, definitely.

**Comment by spiyer99** [comment]
Hi @ricardoV94, thanks for your help. I submitted another PR (#581) as this one was becoming a bit too messy. I hope that’s alright. 

The new PR has two commits, one for moving the `opt` and the second seeding the moved test. 

It also takes into account the `*local*` functions as well as the `SetSubtensor`, `IncSubtensor`, and `Advanced` variations. Please let me know if I’ve missed anything.

**Comment by ricardoV94** [comment]
Yeah that's fine

**Comment by brandonwillard** [comment]
Isn't this supposed to be closed by #581?  Looks like it's already closed, though.

**Pull request closed without merging**
