### PR TITLE
Add `ChiSquareRV` JAX implementation

### LINKED ISSUE #1322: Add JAX implementation for `ChiSquareRV`

### PR DESCRIPTION
**Pull request by larryshamalama**
Closes #1322

Given the shape/rate parametrization of [`GammaRV`](https://github.com/aesara-devs/aesara/blob/main/aesara/tensor/random/basic.py#L453-L456) in Aesara, this addition uses the fact that $$\chi^2_{\text{df}} \equiv \Gamma\left(\frac{\text{df}}{2}, \frac{1}{2} \right).$$

Wiki reference [here](https://en.wikipedia.org/wiki/Chi-squared_distribution#Gamma,_exponential,_and_related_distributions)

### CODE REVIEW

**Comment by rlouf** [comment]
Looks good, waiting for #1345 to be merged to update the key splitting mechanism.

**Review by rlouf — DISMISSED** [review]

**Comment by rlouf** [comment]
Thanks for your contribution @larryshamalama!

**Comment by rlouf** [comment]
I am unable to reproduce the test failure locally (it even works with smaller a smaller number of samples). We need to understand what causes this.

**Comment by larryshamalama** [comment]
I can have a look later, but I'm currently on vacation until early March so I will only be able to do so then. Admittedly, I have not looked much into this PR after its inception...

**Comment by rlouf** [comment]
I don't think the failures have anything to do with your implementation; the tests pass locally for me.

**Comment by brandonwillard** [comment]
Thanks, @larryshamalama!

**Pull request merged**
