### PR TITLE
Remove libgpuarray

### PR DESCRIPTION
**Pull request by ferrine**
Removing all the mentions to libgpuarray

### CODE REVIEW

**Comment by twiecki** [comment]
Can't believe the code-base is getting a smooth 50k LOC lighter.

**Comment by ferrine** [comment]
@brandonwillard I removed a lot of stuff related to GPUs, modified docstring to at least represent it does not work on GPU. There were places that were claiming they work for GPU so I removed these mentions all at once because we do not support that anymore. Same for tests, I worked on making them CPU only and verified it is impossible to misspecify the cuda/gpu device in config. 

Is there anything else left to refactor?

**Review by brandonwillard — COMMENTED** [review]
I've added a few more documentation updates and cleaned up the commits.  If this passes, we can probably merge it.  This is a big one, so we should probably have a couple more people look over it before merging, though.

**Comment by twiecki** [comment]
While I didn't go through it line-by-line I have kept checking things periodically and skimmed it and didn't spot anything that looked misplaced :+1:. Hope we can merge this soon so that we don't have to keep solving conflicts.

**Comment by brandonwillard** [comment]
All right, we have to get this through before the need to constantly rebase grows.

@ferrine, thanks a lot; this was a huge push!

**Comment by ferrine** [comment]
Great

**Pull request merged**
