### PR TITLE
gh: refactor community files

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
This PR aims to move the `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` files from the root of the directory to the `.github/` directory. Github looks for a contribution guideline file in the following order: `.github dir > project root > docs dir` ([source](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)). Moving the file to the `.github/` dir leads to a minimal project structure without any functional change.

### CODE REVIEW

**Comment by dgerlanc** [comment]
Do we have any links to these documents that need updating?

**Review by dgerlanc — CHANGES_REQUESTED** [review]
Can you squash these all into a single commit and rebase on top of the `main` branch?

If you're not comfortable doing that feel free to message me and I can walk you through doing it.

**Comment by SauravMaheshkar** [comment]
> Can you squash these all into a single commit and rebase on top of the `main` branch?
> 
> If you're not comfortable doing that feel free to message me and I can walk you through doing it.

Yes thank you, can you walk me through it.

**Comment by dgerlanc** [comment]
> > Can you squash these all into a single commit and rebase on top of the `main` branch?
> > If you're not comfortable doing that feel free to message me and I can walk you through doing it.
> 
> Yes thank you, can you walk me through it.

Happy to do so - feel free to hit me up on Element (@dgerlanc:matrix.org) or the Aesara Discord room (`dgerlanc`) and we can find a time.

**Comment by dgerlanc** [comment]
> > > Can you squash these all into a single commit and rebase on top of the `main` branch?
> > > If you're not comfortable doing that feel free to message me and I can walk you through doing it.
> > 
> > 
> > Yes thank you, can you walk me through it.
> 
> Happy to do so - feel free to hit me up on Element (@dgerlanc:matrix.org) or the Aesara Discord room (`dgerlanc`) and we can find a time.

I merged these into one commit so that the links aren't broken in any of the commits. Feel free to hit me up still if you want to go over how I did in `git`.

**Comment by SauravMaheshkar** [comment]
> broken in any of the commits. Feel free to hit me up still if you want to go over how I did in `git`.

thank you 😄

**Review by dgerlanc — APPROVED** [review]

**Pull request merged**
