### PR TITLE
Change use of "optimize" to "rewrite"

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR introduces a lot of refactoring that changes object names and comments to use the term "rewrite" instead of "optimize" when appropriate.

Also, modules with the name `opt`&mdash;or a prefix/suffix of `opt`&mdash;have either been renamed to `rewriting` or moved to a sub-package with that name.

### CODE REVIEW

**Review by ricardoV94 — DISMISSED** [review]
Some of the new names sound much more intuitive now.

**Comment by brandonwillard** [comment]
The naming and interfaces of `NodeProcessingGraphRewriter`, `WalkingGraphRewriter`, and perhaps a few other are still a mess, but we can/should go forward with these changes first.

**Comment by brandonwillard** [comment]
@aesara-devs/aesara, all right, I'm going to merge this, which means that we'll need to update the other `aesara-devs` projects and PyMC in order to remove the new deprecation warnings.

**Comment by michaelosthege** [comment]
> @aesara-devs/aesara, all right, I'm going to merge this, which means that we'll need to update the other `aesara-devs` projects and PyMC in order to remove the new deprecation warnings.

👍

This is going to be Aesara 2.8.0 then?

**Comment by brandonwillard** [comment]
> This is going to be Aesara 2.8.0 then?

Yes, definitely.

**Comment by oscarbenjamin** [comment]
It seems this makes some deprecated names unavailable from the packages where they were previously available e.g.:
```
In [1]: import aesara

In [2]: aesara.tensor
Out[2]: <module 'aesara.tensor' from '/home/oscar/current/sympy/sympy.git/38venv/lib/python3.8/site-packages/aesara/tensor/__init__.py'>

In [3]: aesara.tensor.abs_
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-f120198d92d4> in <module>
----> 1 aesara.tensor.abs_

AttributeError: module 'aesara.tensor' has no attribute 'abs_'

In [4]: aesara.tensor.math.abs_
<ipython-input-4-8f09823c3c05>:1: DeprecationWarning: `abs_` is deprecated; use `abs` instead.
  aesara.tensor.math.abs_
Out[4]: <aesara.tensor.elemwise.Elemwise at 0x7fa9c1990eb0>
```
That leads to a test failure in SymPy CI due to this line:
https://github.com/sympy/sympy/blob/88664e6e0b781d0a8b5347896af74b555e92891e/sympy/printing/aesaracode.py#L22

Is it always safe to use `abs` insteaed of `abs_` including with older versions of Aesara and also Theano?

**Comment by brandonwillard** [comment]
> Is it always safe to use `abs` insteaed of `abs_` including with older versions of Aesara and also Theano?

It's not safe for Theano and only up to https://github.com/aesara-devs/aesara/commit/430d068d029a11a92e29f23a2e6065c662022301 in Aesara.

**Comment by brandonwillard** [comment]
@oscarbenjamin, we can probably add deprecation support for `aesara.tensor.abs_`, if that helps.  Regardless, thanks for keeping up on this!

**Pull request merged**
