### PR TITLE
Remove custom standard RV `Op`(s) and add remaining "standard" NumPy RVs

### LINKED ISSUE #1358: Add standard_cauchy, standard_gamma, standard_t and standard_exponential `RandomVariable`
We want to re-use the existing `GammaRV`, `CauchyRV`, `StudentTRV` `ExponentialRV`. The implementation of `StandardNormalRV` may need to be updated.

### PR DESCRIPTION
**Pull request by Smit-create**
Fixes #1358 

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [x] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [x] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [x] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.
+ [x] There are tests covering the changes introduced in the PR.

### CODE REVIEW

**Review by brandonwillard — COMMENTED** [review]
We really need to do something about the existing `StandardNormalRV` (i.e. https://github.com/aesara-devs/aesara/pull/530), because I believe the new class approach was taken due to its convenience with regard to `RandomStream` (i.e. it works with the current `RandomStream.__getattr__` implementation).  See https://github.com/aesara-devs/aesara/issues/528.

In general, we don't want to add new `Op` classes if we don't have to, especially in cases like this where the new `Op` type implies that its corresponding `Apply` nodes will have specific inputs, but there is nothing enforcing this constraint.  One reason this approach is problematic: an `Apply` using a `StandardNormalRV` `Op` can be rewritten to have non-zero mean and/or non-unit variance.  This implies that `StandardNormalRV` is redundant at best, but can also be misleading.  (Likewise, adding input constraints to fix this wouldn't help our graph representations in any foreseeable way; if anything, it would unnecessarily complicate things.)

That said, we should first see what can be done about making `RandomStream` work with simple definitions like `standard_normal = normal(0, 1)` and the `partial` functions.

**Comment by Smit-create** [comment]
Ah, the failure on CI is hard to reproduce on my machine. It says:
```
FAILED tests/link/jax/test_random.py
```

But `pytest` does pass for that on my setup.

**Comment by brandonwillard** [comment]
> But `pytest` does pass for that on my setup.

This is often due to version mismatches between local environments and CI.

**Comment by brandonwillard** [comment]
The issue should be fixed in https://github.com/aesara-devs/aesara/pull/1464.

**Review by brandonwillard — APPROVED** [review]
I added a fix for the use of `partial` functions in `RandomStream` and rebased.  This should be good to merge once the tests pass.

**Pull request merged**
