### PR TITLE
Replace `aet` aliases with `at`

### PR DESCRIPTION
**Pull request by twiecki**
Closes https://github.com/aesara-devs/aesara/issues/328.

This is the command I ran:
```bash
find ./ -type f -exec sed -i -e 's/aet/at/g' {} \;
```

### CODE REVIEW

**Review by brandonwillard — COMMENTED** [review]
Good thing there aren't many/any words with "aet" in them.  

Anyway, the refactor sounds good to me, but someone will need to take a quick look over the changes and make sure we didn't miss something that doesn't show up in the tests.  I might not get to it today, but if anyone else in @aesara-devs/aesara wants to do it, don't hesitate.

**Review by kc611 — APPROVED** [review]
LGTM! Doesn't look like there are any unexpected changes. 

One more thing, should we be doing the same for `aesara.scalar` i.e. `aes` -> `as` ?

**Comment by ricardoV94** [comment]
> LGTM! Doesn't look like there are any unexpected changes. 
> 
> One more thing, should we be doing the same for `aesara.scalar` i.e. `aes` -> `as` ? 

`as` is a Python syntax word (not sure if hard or soft reserved), so probably not. Anyway scalar is mostly used internally so it shouldn't matter if it's more verbose

**Comment by twiecki** [comment]
Thanks @kc611, I rebased to solve the conflicts and merge once tests pass.

**Comment by twiecki** [comment]
@kc611 Need a new approval.

**Review by kc611 — APPROVED** [review]

**Pull request merged**
