### PR TITLE
Remove defaults channel from conda env for docs

### PR DESCRIPTION
**Pull request by maresb**
All the packages are available through conda-forge, and mixing different channels is just a recipe for trouble.

Motivation: for reasons which I don't understand, building the docs has been failing with a 404 error for the `defaults` Conda channel. But everything is available from the `conda-forge` channel, so having the `defaults` channel is pointless. Moreover, if anything does sneak in through the `defaults` channel, it may cause conflicts with the `conda-forge` packages. Thus it's best to just remove it.

**Thank you for opening a PR!**

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [X] There is an informative high-level description of the changes.
+ [ ] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [X] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [X] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [X] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.
+ [ ] There are tests covering the changes introduced in the PR.

Don't worry, your PR doesn't need to be in perfect order to submit it.  As development progresses and/or reviewers request changes, you can always [rewrite the history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) of your feature/PR branches.

If your PR is an ongoing effort and you would like to involve us in the process, simply make it a [draft PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests).

### CODE REVIEW

**Comment by maresb** [comment]
!?!?!? How did that not work? :thinking:

**Comment by maresb** [comment]
I am really confused. Where is this ReadTheDocs workflow even being registered? I see nothing about it in `.github/workflows`.

image

**Comment by brandonwillard** [comment]
See the comment [here](https://matrix.to/#/!QqFchLNQAbmeuhDMrX:gitter.im/$Q7ahD2HNIIItMHbepcYt_c5O3BadNnMknlaTNA-zVxI?via=matrix.org&via=gitter.im).

**Comment by maresb** [comment]
Ok, the missing piece for me was the [Conda Support](https://docs.readthedocs.io/en/stable/guides/conda.html) page for Read the Docs.

**Review by brandonwillard — DISMISSED** [review]

**Comment by maresb** [comment]
Thanks @brandonwillard for the approval! Shall I squash and merge?

**Comment by brandonwillard** [comment]
> Thanks @brandonwillard for the approval! Shall I squash and merge?

Looks like there's a merge commit in there, so you might need to rebase first, then squash and merge.

**Comment by maresb** [comment]
Ok, but what's the rationale? If I squash and merge then it doesn't matter, right?

**Comment by brandonwillard** [comment]
> Ok, but what's the rationale? If I squash and merge then it doesn't matter, right?

If the squash and merge action leaves a linear history, then it should be fine, but I don't know how GitHub's "Squash and merge" handles those situations.

**Comment by maresb** [comment]
I'm pretty sure it does the right thing, but I'll do it by hand just to be safe...

**Review by brandonwillard — APPROVED** [review]

**Comment by brandonwillard** [comment]
Just so we're clear, those two commits can just be "Rebased and merged".

**Comment by maresb** [comment]
As would be done by pressing
image
?

**Comment by maresb** [comment]
(It should now be rebased on the current head of main.)

**Comment by brandonwillard** [comment]
> As would be done by pressing image ?

No, the "Rebase and merge" button this time, because the two commits in this PR appear to be separate enough changes, so we might as well keep them as is.  Really, it's not a big deal in this exact case, so you can do whichever you want.

**Comment by maresb** [comment]
Ah, ok, got it! Thanks for the clarification.

**Pull request merged**
