### PR TITLE
Remove support for Python 3.7

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR removes explicit Python 3.7 support.

### CODE REVIEW

**Comment by maresb** [comment]
@brandonwillard, I rebased on main to fix the mypy failure.

I updated the upper Python version in the test matrix to 3.11. If it was deliberate to have it only at 3.10 then we can remove [0107efc](https://github.com/aesara-devs/aesara/pull/1483/commits/0107efc3e97a94f7202283b21acc6126ad3c0729). Otherwise we might squash it.

Finally I upgraded the flake8 pre-commit version and removed the respective comment in a separate commit.

**Comment by maresb** [comment]
> If it was deliberate to have it only at 3.10 then we can remove [0107efc](https://github.com/aesara-devs/aesara/pull/1483/commits/0107efc3e97a94f7202283b21acc6126ad3c0729).

Ah, right. Numba doesn't yet support 3.11. I'll add a comment.

**Review by maresb — APPROVED** [review]
Waiting on test results, but LGTM

**Comment by brandonwillard** [comment]
Thanks as always, @maresb!

**Pull request merged**
