### PR TITLE
Add JAX dispatch for SolveTriangular Op

### LINKED ISSUE #846: Implement JAX dispatch for `SolveTriangular` `Op`

### PR DESCRIPTION
**Pull request by zaxtax**
This adds a JAX dispatch for the SolveTriangular Op. The unit test isn't the most thorough but it should be sufficient for now.

Resolves #846

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [x] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [x] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [x] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.
+ [x] There are tests covering the changes introduced in the PR.

### CODE REVIEW

**Comment by ricardoV94** [comment]
> The unit test isn't the most thorough but it should be sufficient for now.

What is missing in your opinion?

**Comment by zaxtax** [comment]
Oh I just don't test all the keyword arguments. It's just the default call.

**Comment by zaxtax** [comment]
Should I add more thorough tests before this is merged? Not too much stuff is doing that when testing Ops right now.

**Comment by ricardoV94** [comment]
> Should I add more thorough tests before this is merged? Not too much stuff is doing that when testing Ops right now.

Doesn't hurt to make it just a bit more thorough, so I would say yes

**Comment by ricardoV94** [comment]
@zaxtax can you merge the two commits? We are a bit more strict here in Aesara than in PyMC about PRs having a clean commit history.

**Review by ricardoV94 — APPROVED** [review]

**Pull request merged**
