### PR TITLE
Add `HalfCauchyRV` JAX implementation

### PR DESCRIPTION
**Pull request by theorashid**
This is for #1334. Hopefully it's as obvious as the halfnormal

----------

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [x] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [x] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [x] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.
+ [x] There are tests covering the changes introduced in the PR.

### CODE REVIEW

**Comment by theorashid** [comment]
Also, n00b git question. What the correct git for rebasing and changing the commit name? I f'd it up a bit last time. I just ran `git fetch upstream`
`git rebase upstream/main`

**Comment by rlouf** [comment]
To pull from upstream and rebase `git pull --rebase upstream`.

To rename a commit `git rebase -i`

**Comment by theorashid** [comment]
Well I did the rebase but I made a mess again lol. I'll have a look after the football

**Comment by rlouf** [comment]
Don't hesitate to ask for help!

**Comment by theorashid** [comment]
Hey, yeah I'm not sure how to do this unfortunately. I can only seem to amend the 14 rebase commits rather than the 2 I added. And there's no option to squash. Please let me know how you fix this and I'll never ask again next time I contribute

Also, the workflows are failing but that isn't to do with me by the looks of it. My tests pass locally

**Review by brandonwillard — COMMENTED** [review]
@theorashid, I dropped the merge commit (well, all the commits added by the merge commit), squared the typo fix commit into the original feature commit, and rebased the resulting single commit onto `upstream/main`.  The last step should *not* introduce any new commits.  You can use the command-line interactive rebasing to do the same thing locally; otherwise, you can pull in the changes from your remote branch by rebasing and ignoring any local conflicts.

**Comment by theorashid** [comment]
Great, thank you. This should be good to go

**Comment by rlouf** [comment]
It is only one commit now. Thanks for your contribution!

**Pull request merged**
