### PR TITLE
Fix a numpy deprecation related to dtype

### PR DESCRIPTION
**Pull request by Armavica**
Deprecated in numpy 1.21.0.
This fixes 369 deprecation warnings in PyMC's test suite.

See https://numpy.org/doc/stable/release/1.21.0-notes.html#the-dtype-attribute-must-return-a-dtype

**Thank you for opening a PR!**

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [x] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [x] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [x] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.
+ [x] There are tests covering the changes introduced in the PR.

Don't worry, your PR doesn't need to be in perfect order to submit it.  As development progresses and/or reviewers request changes, you can always [rewrite the history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) of your feature/PR branches.

If your PR is an ongoing effort and you would like to involve us in the process, simply make it a [draft PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests).

### CODE REVIEW

**Review by brandonwillard — COMMENTED** [review]
Thanks for the PR!  I just fixed a similar deprecation warning in https://github.com/aesara-devs/aesara/commit/8867a72094d8df9f7810d091c9856e11edfe693d.  Can you try the same `numpy.obj2sctype` approach from there?  It's appears to be a concise way to determine whether or not a string or `type` is a valid dtype.

**Comment by Armavica** [comment]
I am sorry, but I am not sure how this would work. The function `obj2sctype` doesn't seem to return either a `dtype` or an object whose `.dtype` is a `dtype`, as shown by

``` python
for a in ["float64", np.int8, np.int8(4).dtype]:
    assert not isinstance(np.obj2sctype(a), np.dtype)
    assert not isinstance(np.obj2sctype(a).dtype, np.dtype)
```

**Comment by brandonwillard** [comment]
> I am sorry, but I am not sure how this would work. The function `obj2sctype` doesn't seem to return either a `dtype` or an object whose `.dtype` is a `dtype`, as shown by
> 
> ```python
> for a in ["float64", np.int8, np.int8(4).dtype]:
>     assert not isinstance(np.obj2sctype(a), np.dtype)
>     assert not isinstance(np.obj2sctype(a).dtype, np.dtype)
> ```
> 
> It is possible that I am missing something though, as this dtype manipulation is extremely confusing to me.

Likewise, I'm probably not thinking of the same issue that you are.

Are the deprecation warnings caused by something like the following?
```python
import numpy as np
import aesara.tensor as at


np.dtype(at.vector("x"))
# <ipython-input-11-4480ef785bc5>:1: DeprecationWarning: in the future the `.dtype` attribute of a given datatype object must be a valid dtype instance. `data_type.dtype` may need to be coerced using `np.dtype(data_type.dtype)`. (Deprecated NumPy 1.20)
#   np.dtype(at.vector("x"))
```

**Comment by Armavica** [comment]
Yes, I think that is the idea, at least for some of the warnings.

**Comment by brandonwillard** [comment]
> Yes, I think that is the idea, at least for some of the warnings.

I think I found a test that provides an example of the warnings you're talking about: `pymc/tests/test_logprob.py::test_joint_logp_basic`.  

In that case, `pymc.distributions.logprob.joint_logp` is passing a `TensorType`&mdash;via `var[0].type`&mdash;to the `TensorVariable.astype` method [here](https://github.com/pymc-devs/pymc/blob/193e8679e9307be27232c34df1cefbf87ff6b456/pymc/distributions/logprob.py#L190), when it should be using `var[0].dtype`.

**Comment by Armavica** [comment]
Amazing, it looks like this fixes everything! Thank you very much!

**Pull request closed without merging**
