### PR TITLE
Use `broadcast_to` instead of `broadcast_like`

### LINKED ISSUE #159: Replace broadcast_like with broadcast_to
The function [`broadcast_like`](https://github.com/pymc-devs/Theano-PyMC/blob/master/theano/tensor/opt.py#L169) can be replaced with the new `broadcast_to` function in most&mdash;if not all&mdash;cases.

The `broadcast_to` function uses view-based broadcasting instead of allocating filled arrays as `broadcast_like` does, so this change could introduce performance improvements in many general use situations (more specifically, when the basic algebraic optimizations that use `broadcast_like` are employed).

### PR DESCRIPTION
**Pull request by eigenfoo**
Closes #159. WIP.

Two questions:

1. Changing `broadcast_like` to `broadcast_to` in `aesara/tensor/math_opt.py` gives me a lot of `BadOptimization` and `AssertionErrors`, which I'm not knowledgeable enough to debug - can someone help me understand what's happening?
2. ~I've also changed `broadcast_like` to `broadcast_to` in `aesara/tensor/basic_opt.py` - is this something we want to do?~

### CODE REVIEW

**Comment by eigenfoo** [comment]
Hmm - more tests are failing than I anticipated. Running `pytest tests/tensor/test_math_opt.py` gives me the 9 errors I was originally referring to: https://gist.github.com/eigenfoo/8c2d5e7867fc23b82c98553c5300b054

I'm unsure what happened with `tests/tensor/test_basic.test_alloc_constant_folding`...

**Comment by brandonwillard** [comment]
> The failures don't actually call `broadcast_to`, but most of them involve `toposort` or optimize using `local_pow_canonicalize`, which does call `broadcast_to`. Does that mean `broadcast_to` affected the graph optimizations, which is what these failed tests are testing for?

It looks like they're failing because those unit tests make unnecessarily strong assumptions, aren't isolated/self-contained enough, etc.  In other words, you're seeing the long standing deficiencies of our test suite.

**Comment by brandonwillard** [comment]
Aside from strong test assumptions, there are some optimization errors that are probably worth addressing first; those may actually involve bugs.  

For instance, the first optimization error is implying that the the type generated by the newly introduced `BroadcastTo` `Op` doesn't match the type of the graph it's replacing in the optimization.

**Comment by eigenfoo** [comment]
@brandonwillard the latest commit https://github.com/pymc-devs/aesara/pull/288/commits/6262bd0977051c849fb13f1fc0439592fbb5a72b gets rid of all `BadOptimization` errors, as far as I can tell - all that remains are `AssertionErrors`.

However, I suspect I'm doing something ugly by adding the `dtype` parameter like this - can you take a look at the new parameter? If it all looks good, I'll move on to fixing the tests: I suspect I'll need a lot of help along the way, though 😬

**Review by brandonwillard — CHANGES_REQUESTED** [review]
Can't we simply cast the result of `broadcast_to` to the desired dtype (e.g. using `TensorVariable.astype`)?  

Adding a dtype argument to the `Op` doesn't add much in the way of functionality, and it causes the `Op` to deviate from the underlying `numpy.broadcast_to` that it models/wraps.

**Comment by eigenfoo** [comment]
Sure, that actually makes it easier. I assumed we wanted to mimic the `broadcast_like` signature, which took a `dtype` parameter. Sorry if that was a bad assumption.

The previous two commits revert the `dtype` commit, and use `TensorVariable.astype` to cast dtypes.

**Comment by eigenfoo** [comment]
@brandonwillard I think I've fixed all tests but two. I'm confused about the remaining failures - I've attached the output of `pytest test_math_opt.py` here: https://gist.github.com/eigenfoo/ddb7d2aad30550c0efbf64a1841881f9

1. `test_stacktrace` seems to be a real failure that I don't understand - what exactly is the "trace" that we're testing for? https://github.com/pymc-devs/aesara/blob/master/aesara/graph/opt.py#L3188-L3189
2. What is `test_local_reduce_join` testing for? I can tell that it's only these two lines that are failing the test, but don't know if its safe to remove them, or if this is a real failure... https://github.com/pymc-devs/aesara/blob/0344f1a844731eea980ada631fe180e09f397a51/tests/tensor/test_math_opt.py#L3472-L3473

**Comment by brandonwillard** [comment]
> 1. `test_stacktrace` seems to be a real failure that I don't understand - what exactly is the "trace" that we're testing for?

That's probably referring to the stack traces carried by each variable in their `tag`.  Those traces show where each variable was created, and, during optimizations, they're carried over to newly created replacement variables.  Their only real purpose is for user-level debugging.

**Comment by brandonwillard** [comment]
> 2\. What is `test_local_reduce_join` testing for? I can tell that it's only these two lines that are failing the test, but don't know if its safe to remove them, or if this is a real failure...

Those looks like brittle test conditions.  Instead of coming up with a direct check for something specific and relevant in the transformed graph, many tests will simply `assert` the number of nodes in the expected output.

In almost all cases, these kinds of `assert`s are simply bad, so don't take them too seriously.  If you changed an optimization, an `Op`, and/or one of an `Op`'s helper functions, and any of those things are used in one of these tests, then a change in the number of nodes could be easily justified.

**Comment by brandonwillard** [comment]
I'll try running these tests locally within the next few days and see if I can spot any genuine issues (i.e. ones that aren't due to brittle/overly-restrictive tests).

**Comment by eigenfoo** [comment]
Thanks for helping @brandonwillard! Sorry for being so slow-moving on this PR - something has popped up in the real world (and not a lack of interest in finishing this work).

I've loosened the test conditions on `test_local_reduce_join` so that it passes now, and I've removed `test_stacktrace` entirely. I'm unsure why `test_stacktrace` fails whereas a similar test, `test_local_sum_prod_mul_by_scalar_stack_trace`, succeeds. I'd be happy to put the test back if I could get a pointer on what's gone wrong.

I'll wait for the test suite to finish, but I'd also appreciate a quick triage of whether there are other real test failures - otherwise I'll assume that everything that fails is a flaky test.

**Comment by brandonwillard** [comment]
> Sorry for being so slow-moving on this PR

I only commented so that you knew I hadn't forgotten about this PR; there's absolutely no rush, though!

**Comment by eigenfoo** [comment]
@brandonwillard `test_basic/test_stack_hessian` is failing - this seems like a real failure, but I'm unsure what's going wrong. Could you give some pointers?

https://github.com/pymc-devs/aesara/pull/288/checks?check_run_id=1884844321

**Comment by brandonwillard** [comment]
> `test_basic/test_stack_hessian` is failing - this seems like a real failure

Yes, that does look like a real issue.  My first impression was that it had to do with in-place operations.  

The new `broadcast_to` uses NumPy's underlying view-based broadcasting via the `BroadcastTo` `Op`, and its [`view_map`](https://github.com/pymc-devs/aesara/blob/bd54469c7833e2a8c21751e97b7cdd299080dc99/aesara/tensor/extra_ops.py#L1551) is supposed to indicate the view relationship between the `Op`'s first input, `a`, and its output.  Given that the first value is 2, as expected, and all the remaining values are effectively 0, it seemed like an optimization might've been ignoring this view information and "in-placing" things that it shouldn't.

Unfortunately, the evaluated graph doesn't contain any `BroadcastTo` `Op`s, so, if the problem is related to `BroadcastTo`-generated views, it's manifesting in an indirect way.

**Comment by brandonwillard** [comment]
OK, the issue _does_ appear to involve bad in-placing.  Those `FunctionGraph` validation failures are specifically caused by `aesara.tensor.basic_opt.local_inplace_setsubtensor` producing the following exception:
```python
InconsistencyError('Attempting to destroy indestructible variables: [TensorConstant{(1,) of 0.0}]')
```

**Comment by brandonwillard** [comment]
All right, I believe that the source of this issue is the change from `broadcast_like` to `broadcast_to` in `aesara.tensor.basic_opt.local_fill_to_alloc`.  That's the rewrite that introduces the `BroadcastTo` `Op` in the first place.

In this case, a `fill` really shouldn't be replaced with a broadcasted view of the fill value; however, we might want a rewrite that turns unmodified (in-place) `alloc`s and/or `fill`s into `BroadcastTo`s.

**Comment by brandonwillard** [comment]
Now that I think about it, we could probably use a simple optimization that removes useless `BroadcastTo`s.

**Comment by brandonwillard** [comment]
Looks like there are a few more brittle tests (e.g. `TestCrossEntropyCategorical1Hot.test_get_rid_of_advanced_indexing_version_of_xent _` does the same `len(topo) == x` nonsense).

**Comment by brandonwillard** [comment]
Also, some of these optimizations might be having trouble because `BroadcastTo` isn't being lifted.  

In the case of `TestMinMax.test_optimization_min`, it looks like the optimizations being tested aren't applied because they're looking for `neg(max(neg(...)))`, but now the graph is `neg(max(broadcast_to(neg(...))))`.  If we lift the `BroadcastTo` `Op`s, it should fix that.

**Comment by ricardoV94** [comment]
Just rebased this PR

**Pull request closed without merging**
