### PR TITLE
Remove `TensorConstant.tag.unique_value`

### PR DESCRIPTION
**Pull request by Carlosbogo**
Replaced TensorConstant.tag.unique_value by method TensorConstant.get_unique_value()

It is my first PR so I might have done something wrong. If so, please tell me and I will be glad to help with everything I can.

### CODE REVIEW

**Review by brandonwillard — CHANGES_REQUESTED** [review]
Much appreciated!

I removed a file that was accidentally added to the commit.  You'll need to squash the commit I just added so that only the one original commit message remains.

Otherwise, the changes look good.  The only thing I'm not sure of is whether or not this should be a new method.  There's nothing _wrong_ with it being a new method necessarily, but, given its use (e.g. with objects that might only be `Constant`s) and limited utility, it would be better as a stand-alone function.

**Comment by brandonwillard** [comment]
Oh, you may also need to set up `pre-commit` (e.g. `pip install -r requirements.txt` and then `pre-commit install`); that will help catch the current errors locally.

**Comment by Carlosbogo** [comment]
About making it a stand-alone function, I am wondering about where should the definition of the function be, in order to keep things as organised as possibl, as there are many different .py files.

I will try to change that and then rebase and squash the commit you added.

**Comment by brandonwillard** [comment]
> About making it a stand-alone function, I am wondering about where should the definition of the function be, in order to keep things as organised as possible, as there are many different .py files.
> 
> I will try to change that and then rebase and squash the commit you added.

Sorry for the delay; `aesara.tensor.basic` is a good place for such a function&mdash;that's where the most similar functions currently reside (e.g. `get_scalar_constant_value` and `extract_constant`).

If you need any help rebasing/squashing, don't hesitate to ask.  Also, if you'd like, I can do that for this branch, but you would then need to [rebase/reset your local branch](https://stackoverflow.com/a/25518935/3006474) to pull in those changes.

**Review by brandonwillard — COMMENTED** [review]
> About making it a stand-alone function, I am wondering about where should the definition of the function be, in order to keep things as organised as possible, as there are many different .py files.
> 
> I will try to change that and then rebase and squash the commit you added.

Sorry for the delay; `aesara.tensor.basic` is a good place for such a function&mdash;that's where the most similar functions currently reside (e.g. `get_scalar_constant_value` and `extract_constant`).

If you need any help rebasing/squashing, don't hesitate to ask.  Also, if you'd like, I can do that for this branch, but you would then need to rebase/reset your local branch (e.g. like [this](https://stackoverflow.com/a/25518935/3006474), but with `origin/master` replaced with something like `origin/update_constant_unique_value`) to pull in those changes.

**Review by brandonwillard — APPROVED** [review]

**Pull request merged**
