### PR TITLE
Updates to linear algebra `Op`s

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR provides updates to the `aesara.tensor.[n|s]linalg` modules.  

It removes the conditional logic for the presence of SciPy, automatically makes `slinalg` available from `aesara.tensor`, and updates `Solve` to use the current SciPy arguments/options, adds an `Op` for `numpy.linalg.inv`, adds the `hermitian` option to `MatrixPinv`, and a `MatrixPinv.infer_shape` implementation.

### CODE REVIEW

**Comment by twiecki** [comment]
I wonder if we should merge `nlinalg` and `slinalg` into just `linalg`. I think the reason that they did that was that they wanted to have `scipy` be an optional dependency.

**Comment by brandonwillard** [comment]
> I wonder if we should merge `nlinalg` and `slinalg` into just `linalg`. I think the reason that they did that was that they wanted to have `scipy` be an optional dependency.

I would like to do this, but combining those would make for one large file, and, since the NumPy/SciPy division is at least consistent, it's probably better if we keep them separate.  At the very least, it will relieve some pressure on our editors.

**Comment by ricardoV94** [comment]
> I would like to do this, but combining those would make for one large file, and, since the NumPy/SciPy division is at least consistent, it's probably better if we keep them separate.  At the very least, it will relieve some pressure on our editors.

What about having linalg just exposed the methods from the two files?

**Comment by brandonwillard** [comment]
> What about having linalg just expose the methods from the two files?

Yeah, I was considering adding a stub `linalg` module we could expose exclusively for interface purposes.

**Pull request merged**
