### PR TITLE
Make `TensorConstant`s print their names when specified

### LINKED ISSUE #689: Use constant names when specified
```python
import aesara.tensor as at

z = at.constant(1, name='z')

print(z)  
# TensorConstant{1}

aesara.dprint(z)  
# TensorConstant{1} [id A]
```

In contrast:
```python
z = at.scalar('z')

print(z)  
# z

aesara.dprint(z) 
# z [id A]
```

Or:
```python
z = at.constant(1, name='z')
y = z + 1; 
y.name = 'y'

print(y)  
# y

aesara.dprint(y)
# Elemwise{add,no_inplace} [id A] 'y'   
#  |TensorConstant{1} [id B] <-- We could show 'z' here
#  |TensorConstant{1} [id C]
```

### PR DESCRIPTION
**Pull request by oscargus**
In addition, the value is printed (and sometimes the data type).

I modified it a bit to also print the value, but easy to change if the original proposal in #689 is deemed better. I imagined that it may be better to get more information, but on the other hand the name is there, so maybe no benefit.

Example:
```
In [9]: z = at.constant(1, name='z')
   ...: y = z + 1; 
   ...: y.name = 'y'

In [10]: dprint(y)
Elemwise{add,no_inplace} [id A] 'y'   
 |z{1} [id B]
 |TensorConstant{1} [id C]

In [11]: print(z)
z{1}
```

**Thank you for opening a PR!**

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [x] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [x] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [x] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.
+ [x] There are tests covering the changes introduced in the PR.

Don't worry, your PR doesn't need to be in perfect order to submit it.  As development progresses and/or reviewers request changes, you can always [rewrite the history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) of your feature/PR branches.

If your PR is an ongoing effort and you would like to involve us in the process, simply make it a [draft PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests).

### CODE REVIEW

**Comment by brandonwillard** [comment]
Thanks again, @oscargus!

**Comment by ricardoV94** [comment]
This breaks a bit with how other variable names are displayed in the `dprint` (after the `id`)

**Comment by oscargus** [comment]
> This breaks a bit with how other variable names are displayed in the `dprint` (after the `id`)

Ahh, now I understand how it was meant to be for that case... (I had a quick look at debugprint and, well, it was not straightforward from a quick look how it works...) As I understands it, the first part is simply the `str` of the object, id, and then name. But, well, it works for the expression so should be possible to solve for TensorConstant as well.

**Comment by ricardoV94** [comment]
> > This breaks a bit with how other variable names are displayed in the `dprint` (after the `id`)
> 
> Ahh, now I understand how it was meant to be for that case... (I had a quick look at debugprint and, well, it was not straightforward from a quick look how it works...) As I understands it, the first part is simply the `str` of the object, id, and then name. But, well, it works for the expression so should be possible to solve for TensorConstant as well.

Do you want to try it in a followup PR?

**Comment by oscargus** [comment]
> Do you want to try it in a followup PR?

I think it should be quite straightforward, except for a fundamental issue. 

Right now it prints as:
https://github.com/aesara-devs/aesara/blob/20581c3f4281483f7763a19d104fd83bb2031d7b/aesara/printing.py#L572

It is straightforward to change this to something like:
https://github.com/aesara-devs/aesara/blob/20581c3f4281483f7763a19d104fd83bb2031d7b/aesara/printing.py#L484
i.e. add a `'r.name'` in the correct place.

`print(r)` and the `{r}` part in the first line will out of necessity give the same output. So the option is to provide a new property, `_debug_print` that gives the `TensorConstant{1}` string (the `__str__` method can then return that if name is not defined).

I should admit that I have not used aesara, but just wanted to fix the NumPy issue for SymPy reasons, so I do not really know about all the different cases that may end up here, but to get something that prints as expected for `TensorConstant` (and hopefully doesn't break anything else) should be quite doable.

Are there some more complex example expressions to play around with somewhere?

**Comment by brandonwillard** [comment]
> This breaks a bit with how other variable names are displayed in the `dprint` (after the `id`)

Only in that it adds/retains the data print-out, but that's fine, because `Constant`s are the only type of `Variable` that have data elements to print in the first place (aside from their shared counterparts, of course), so there isn't a relevant precedence there.

Otherwise, with regard to `dprint` printing the name after the `id` block, that isn't relevant here, because `Constant`s don't have "owners" (i.e. they aren't the outputs of an `Apply` nodes, they're "atomic"), and that style of name printing is only applicable to `Variable`s with owners.

Under this PR we get the following:
```python
import aesara
import aesara.tensor as at


z = at.constant(1, name='z')
aesara.dprint(z * 2)
# Elemwise{mul,no_inplace} [id A] ''
#  |z{1} [id B]
#  |TensorConstant{2} [id C]

a = at.scalar("a")
aesara.dprint(a * 2)
# Elemwise{mul,no_inplace} [id A] ''
#  |a [id B]
#  |TensorConstant{2} [id C]
```

Again, the only difference is that the `Constant` will also print its value, which has been the standard for a while.  Now, the name _and_ the value are printed, which is perfectly fine and doesn't break with anything.

**Pull request merged**
