### PR TITLE
Add F RandomVariable

### LINKED ISSUE #1366: Add f `RandomVariable`
https://numpy.org/doc/stable/reference/random/generated/numpy.random.f.html

### PR DESCRIPTION
**Pull request by aadya940**
Fixes #1366 

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [x] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [x] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [x] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.
+ [x] There are tests covering the changes introduced in the PR.

### CODE REVIEW

**Comment by brandonwillard** [comment]
Much appreciated @aadya940!

**Comment by aadya940** [comment]
I guess the test's are failing due to an issue in sphinx. Can someone please review the code before we can merge it?

**Comment by brandonwillard** [comment]
I've fixed the formatting issues and squashed the commits.

**Comment by brandonwillard** [comment]
@aadya940, many thanks for the contribution!

**Comment by aadya940** [comment]
> @aadya940, many thanks for the contribution!

Welcome :-)

**Pull request merged**
